[project]
name = "f1-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.5.3",
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
]
